Subscribe Card
tt-dev-23/Yuriy2437_Practice pull request #10
Opened 2023-07-10 17:23 UTC by Yuriy2437

Верстка карточки с подпиской, #5

2023-07-11 21:59 UTC, foxprogs commented on subscribe_card/index.html
> +          <h5 class="text content">
для чего тут два класса?

2023-07-11 22:00 UTC, foxprogs commented on subscribe_card/index.html
> +          <div class="input_btn">
лучше назвать это форма или форма подписки

2023-07-11 22:01 UTC, foxprogs commented on subscribe_card/index.html
> +        <div class="text_part">
у нас есть карточка, у нее картинка и я бы назвал  контент. Тут же не только текст, тут и форма есть еще

2023-07-11 22:03 UTC, foxprogs commented on subscribe_card/index.html
> +          <h5 class="text content">
это текст, тут правильнее было бы использовать параграф. И не обязательно всему давать классы. Мы же можем написать `.content p` к примеру

2023-07-11 22:03 UTC, foxprogs commented on subscribe_card/index.html
> +            <input type="email" class="email btn_style" placeholder="Enter your email address" />
не логично что у инпута класс стиль кнопки. Надо переделать

2023-07-11 22:05 UTC, foxprogs commented on subscribe_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/248798887-21bf58b0-121d-4b12-83aa-b476992a5cb5.png" class="btn btn_style">Subscribe</a>
если говорить об интерфейсах, то лучше всегда стараться прописывать для кнопки стиль по наведению и по нажатию. Чтобы была какая-то интерактивность.

2023-07-11 22:06 UTC, foxprogs commented on subscribe_card/styles.css
> +@import url("https://fonts.googleapis.com/css2?family=Vidaloka&display=swap");
для чего Vidaloka подключен в 1 и 3 строке

2023-07-11 22:07 UTC, foxprogs commented on subscribe_card/styles.css
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Vidaloka&display=swap");
зачем тут подключен Roboto и не используется в итоге.

2023-07-11 22:08 UTC, foxprogs commented on subscribe_card/styles.css
> +  font-family: "Arial", sans-serif;
Arial это шрифт виндовс, у меня к примеру на линукс такого нет по этому используется sans-serif. Лучше использовать или семейство шрифтов или подключить с гугла сразу

2023-07-11 22:10 UTC, foxprogs commented on subscribe_card/styles.css
> +  background-color: #303037;
можно попробовать использовать css переменные чтобы не писать одно и то же 3 раза. Если вдруг придется завтра чуть поменять цвет, придется это делать в 3 местах. А если это будет переменная - то только в одном

2023-07-11 22:12 UTC, foxprogs commented on subscribe_card/styles.css
> +  padding: 3.1rem 2rem 6.5rem 2.31rem;
почему такой большой отступ снизу, 6.5rem.
![image](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/96c893af-f8c3-41e8-b423-041ea34a0c43)
Вообще тут логика отступов мне непонятна. Почему они именно такие. Тем более что они сейчас не работают так как сама карточка больше

2023-07-11 22:16 UTC, foxprogs commented on subscribe_card/styles.css
> +  height: 16.8rem;
вот это надо убрать и тогда будет видно что те большие пэддинги у text_part сильно увеличивают карточку.

2023-07-13 08:46 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  padding: 3.1rem 2rem 6.5rem 2.31rem;
убрал ширину и длину карточки, изменил отступы на padding: 3.4rem 3.94rem 3.6rem 2.33rem;

2023-07-13 08:47 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  height: 16.8rem;
убрал и ширину, и длину карточки; все сделал через отступы

2023-07-13 08:59 UTC, Yuriy2437 commented on subscribe_card/index.html
> +          <h5 class="text content">
убрал класс text

2023-07-13 09:31 UTC, Yuriy2437 commented on subscribe_card/index.html
> +          <div class="input_btn">
Изменил название класса на form

2023-07-13 09:37 UTC, Yuriy2437 commented on subscribe_card/index.html
> +        <div class="text_part">
Изменил text_part на content, а content на text

2023-07-13 10:15 UTC, Yuriy2437 commented on subscribe_card/index.html
> +            <input type="email" class="email btn_style" placeholder="Enter your email address" />
Изменил btn_style на form_style

2023-07-13 10:22 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +@import url("https://fonts.googleapis.com/css2?family=Vidaloka&display=swap");
убрал 1 строку

2023-07-13 10:23 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Vidaloka&display=swap");
заменил Arial на Roboto

2023-07-13 10:23 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  font-family: "Arial", sans-serif;
заменил Arial на Roboto

2023-07-13 10:39 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  background-color: #303037;
Использовал переменную для цвета в card и email

2023-07-13 10:55 UTC, Yuriy2437 commented on subscribe_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/248798887-21bf58b0-121d-4b12-83aa-b476992a5cb5.png" class="btn btn_style">Subscribe</a>
Добавлены стили для наведения и нажатия кнопки

2023-07-19 10:16 UTC, foxprogs commented on subscribe_card/index.html
> +          <h5 class="text content">
@Yuriy2437 тут я комментарий оставил только к 15 строке, к h5. То что h3 заголовок - это нормально, не стоит его в параграф превращать
Если я пишу комментарий к нескольким строкам то гитхаб это подписывает как к примеру тут
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/cd668a98-5a78-47f6-8cfe-fec19e244b06)

А обычно комментарий к строке, и гитхаб подгружает предыдущие строки для того чтобы был понятен контекст

2023-07-19 10:24 UTC, foxprogs commented on subscribe_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/248798887-21bf58b0-121d-4b12-83aa-b476992a5cb5.png" class="btn btn_style">Subscribe</a>
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/6d31e783-d7b4-44a6-883d-be2aea389437)
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/6bbdf9ca-202c-4dc6-bfb2-9ce0774983cc)
Вот к примеру кнопка у гитхаб - обычная, hover, active, меняется только фон и цвет обводки. Те стили что сейчас, зеленый желтый красный - сильно выбиваются из всего дизайна. Лучше взять оттенки. При наведении чуть темнеее, при нажатии еще темнее.

2023-07-19 10:29 UTC, foxprogs commented on subscribe_card/styles.css
> +  outline: 0.5rem solid #303037;
тут тоже можно переменную использовать же

2023-07-19 10:44 UTC, foxprogs commented on subscribe_card/styles.css
> +  font-family: "Roboto", sans-serif;
в нескосльких местах используется много свойств для font, лучше использовать сокращенный синтаксис тогда

2023-07-19 10:52 UTC, foxprogs commented on subscribe_card/styles.css
> +  height: 2.94rem;
для чего эта высота? С ней тогда пэддинги не работают. Надо это удалить

2023-07-19 10:53 UTC, foxprogs commented on subscribe_card/styles.css
> +}
поменять цвета на более правильные

2023-07-19 16:52 UTC, foxprogs commented on subscribe_card/styles.css
> +@media (min-width: 100px) and (max-width: 499px), (min-width: 500px) and (max-width: 800px) {
а почему такой запрос, от 100 до 499 и от 500 до 800? Это же то же самое что от 100 до 800?

2023-07-19 16:53 UTC, foxprogs commented on subscribe_card/styles.css
> +    background-image: url("Honey-garlic-chicken-meal-prep-6.jpg");
для чего тут повторять снова код и устанавливать фоновую картинку и остальные параметры, которые и так уже установлены?

2023-07-19 19:39 UTC, foxprogs commented on subscribe_card/styles.css
> +@media (min-width: 100px) and (max-width: 499px) {
какой здесь подход к дизайну? От десктопной версии до мобильной?
Тогда для чего ставить минимальные значения? Нужно делать так
```css
/* CSS для >=1200px */

@media (max-width: 1199px) {
  /* CSS для ширины от 992px до 1199px */
}

@media (max-width: 991px) {
  /* CSS для ширины от 768px до 991px */
}

@media (max-width: 767px) {
  /* CSS для ширины от 576px до 767px */
}

@media (max-width: 575px) {
  /* CSS для ширины до 575px (включительно) */
}
```

2023-07-19 19:39 UTC, foxprogs commented on subscribe_card/styles.css
> +@media (min-width: 100px) and (max-width: 499px) {
И смысл в том что мы переопределяем только то что надо. Не нужно заново все стили писать

2023-07-19 19:40 UTC, foxprogs requested changes
Есть комментарии. И надо переписать правильно отзывчивый дизайн

2023-07-24 09:09 UTC, Yuriy2437 commented on subscribe_card/index.html
> +          <h5 class="text content">
Вернул h3 в строку 14

2023-07-24 09:18 UTC, Yuriy2437 commented on subscribe_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/248798887-21bf58b0-121d-4b12-83aa-b476992a5cb5.png" class="btn btn_style">Subscribe</a>
Изменены цвета кнопки по наведению и нажатию

2023-07-24 09:22 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  outline: 0.5rem solid #303037;
Изменено: outline: 0.5rem solid var(--main-bg-color);

2023-07-24 09:36 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  font-family: "Roboto", sans-serif;
В трех местах использована сокращенная запись font

2023-07-24 09:46 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  height: 2.94rem;
удалил height: 2.94rem;

2023-07-24 10:04 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +@media (min-width: 100px) and (max-width: 499px), (min-width: 500px) and (max-width: 800px) {
Изменил на (max-width: 800px)

2023-07-24 10:08 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    background-image: url("Honey-garlic-chicken-meal-prep-6.jpg");
Убрал лишний код из медиа-запроса photo

2023-07-24 10:24 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    background-image: url("Honey-garlic-chicken-meal-prep-6.jpg");
Единый стиль form и form_style в медиа-запросах

2023-07-24 10:37 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    background-image: url("Honey-garlic-chicken-meal-prep-6.jpg");
Удален повторяющийся код из медиа-запроса 500-800

2023-07-24 10:40 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    background-image: url("Honey-garlic-chicken-meal-prep-6.jpg");
Изменено на @media (max-width: 499px)

2023-07-24 10:43 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +@media (min-width: 100px) and (max-width: 499px) {
Изменил код, посмотрите, все ли теперь нормально?

2023-08-01 07:39 UTC, foxprogs commented on subscribe_card/styles.css
> +  font-family: 16px;
а что это за стиль?

2023-08-01 07:49 UTC, foxprogs commented on subscribe_card/styles.css
> +@media (min-width: 100px) and (max-width: 499px) {
Какой подход к дизайну? глобально есть два подхода: mobile first и desktop first. Или сначала мы пишем стили для телефона а потом через медиазапросы переопределяем блоки, или же наоборот. И я привел пример, если делается сначала для пк а потом для телефонов, тут нет min-width никаких. Лучше придерживаться стандартов

2023-08-01 07:59 UTC, foxprogs commented on subscribe_card/styles.css
> +    flex-direction: row;
вот это к примеру не работает потому что не flex
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/45db89ee-799b-4356-bda0-7e51f007515c)

2023-08-01 08:03 UTC, foxprogs commented on subscribe_card/styles.css
> +@media (max-width: 499px) {
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/419e4527-1bc7-45c5-844e-699b6f53b132)
вот тут тоже вижно что два стиля зачем-то два раза написаны

2023-08-01 08:04 UTC, foxprogs commented on subscribe_card/styles.css
> +  .email {
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/d6253bda-1dab-42e7-a754-ad34c09c11b5)
вот тут тоже два раза написано text-align:center

2023-08-05 08:33 UTC, Yuriy2437 commented on subscribe_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/248798887-21bf58b0-121d-4b12-83aa-b476992a5cb5.png" class="btn btn_style">Subscribe</a>
Изменены цвета и оттенки кнопки в изначальном виде, по наведению и нажатию: в точном соответствии с вашим рисунком

2023-08-05 08:37 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  font-family: 16px;
Изменил font-family на font-size

2023-08-05 08:40 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    padding: 0;
Убрал padding: 0; из медиа-запросов btn и email

2023-08-05 09:10 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    text-align: center;
Убрал text-align: center

2023-08-05 09:58 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    flex-direction: row;
Добавил display: flex

2023-08-05 09:59 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +@media (max-width: 499px) {
Убрал text-align: center

2023-08-05 10:00 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  .email {
Убрал text-align: center

2023-08-05 10:26 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +@media (min-width: 100px) and (max-width: 499px) {
Изменил подход к дизайну медиа-запросов: 1) сначала основные стили вне медиа-запросов; 2) затем @media (max-width: 800px); 3) затем @media (max-width: 499px). Минимальные значения удалены. Код идет последовательно: через максимумы, в порядке понижения

2023-08-14 19:53 UTC, foxprogs commented on subscribe_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/248798887-21bf58b0-121d-4b12-83aa-b476992a5cb5.png" class="btn btn_style">Subscribe</a>
@Yuriy2437 это же я просто взял скрины кнопок с гитхаба. Не нужно брать цвета отсюда. Надо просто взять принцип. На картинке я скинул кнопки двух цветов. Видно что оттенки кнопок тут меняются незначительно. В первый раз у вас все менялось очень сильно, менялись цвета. Второй раз мы сделали оттенки, но это было тоже слишком контрастно. Я в комментарии уточнил, что непохоже с тем что на картинке. По этому надо вернуть тот зеленый что и был. И подобрать именно оттенки того зеленого

2023-08-14 20:02 UTC, foxprogs commented
@Yuriy2437 
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/e38a6779-cff0-4117-aa6a-a49e956cf79e)
текст у кнопки не по центру

2023-08-14 20:07 UTC, foxprogs commented on subscribe_card/styles.css
> +  padding: 0.6rem 1rem 0.9em 1.438rem;
почему слева отступ больше чем справа? он же в итоге криво смотрится?

2023-08-14 20:11 UTC, foxprogs commented on subscribe_card/styles.css
> +  padding: 0.6rem 1rem 0.9em 1.438rem;
и для чего пэддинг сверху и снизу если указана высота блока? Какой смысл от них? При том он разный и по этому текст чуть смещен

2023-08-14 20:13 UTC, foxprogs commented on subscribe_card/styles.css
> +    box-sizing: border-box;
для чего? Если оно и так в reset применяется.

2023-08-14 20:15 UTC, foxprogs commented on subscribe_card/styles.css
> +  font: 500 0.9rem "Roboto", sans-serif;
line-height можно указать сразу в font

2023-08-14 20:16 UTC, foxprogs commented on subscribe_card/styles.css
> +    display: flex;
снова тот же вопрос. Зачем писать display: flex если он и так display: flex?
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/78288093-1614-4d25-8638-df3c217f467a)

2023-08-14 20:21 UTC, foxprogs commented on subscribe_card/styles.css
> +    align-items: center;
тут еще печальней выглядит. 
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/80594c0b-6d36-4cf2-b51a-6e2e08ecb02e)
display три раза на flex меняется

2023-08-14 20:24 UTC, foxprogs commented on subscribe_card/styles.css
> +    display: flex;
для чего у инпута указан флекс, у него же ничего вложенного нет

2023-08-14 20:25 UTC, foxprogs requested changes
есть замечания. Нужно так же разобраться как пользоваться devtools браузера, чтобы видеть стили и верстку

2023-08-18 00:20 UTC, Yuriy2437 commented on subscribe_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/248798887-21bf58b0-121d-4b12-83aa-b476992a5cb5.png" class="btn btn_style">Subscribe</a>
Вернул старые цвета в кнопку. Изменил их оттенки по наведению и нажатию

2023-08-18 00:27 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    flex-direction: row;
убрал лишний код из @media (max-width: 800px)

2023-08-18 00:28 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +@media (max-width: 499px) {
убрал лишний код из @media (max-width: 499px)

2023-08-18 00:38 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    box-sizing: border-box;
убрал

2023-08-18 00:42 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  padding: 0.6rem 1rem 0.9em 1.438rem;
вообще убрал отсюда padding

2023-08-18 00:43 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  font: 500 0.9rem "Roboto", sans-serif;
указал

2023-08-18 00:44 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    display: flex;
Вообще убрал form и form_style из этого медиа-запроса

2023-08-18 00:47 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    align-items: center;
В этом медиа-запросе убрал display: flex и justify-content: center. Оставил только flex-direction: column. Изменил align-items: center на align-items: normal

2023-08-18 00:48 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    display: flex;
убрал

2023-08-18 00:58 UTC, Yuriy2437 commented
> есть замечания. Нужно так же разобраться как пользоваться devtools браузера, чтобы видеть стили и верстку

Освоил девтулс. Полностью изменил стили медиа-запросов. Убрал лишнее. Также, теперь видя все с помощью девтулс, убрал лишнее из основного участка кода

2023-08-18 03:08 UTC, Yuriy2437 commented on subscribe_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/248798887-21bf58b0-121d-4b12-83aa-b476992a5cb5.png" class="btn btn_style">Subscribe</a>
Возвращен изначальный цвет кнопок, изменены оттенки по наведению и нажатию

2023-08-18 03:10 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  padding: 0.6rem 1rem 0.9em 1.438rem;
Текст кнопки теперь по центру. Паддинг убрал здесь совсем

2023-08-18 03:11 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    box-sizing: border-box;
убрал border-box

2023-08-18 03:11 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  font: 500 0.9rem "Roboto", sans-serif;
указал

2023-08-18 03:13 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    display: flex;
вообще убрал form и form_style из @media (max-width: 800px)

2023-08-18 03:15 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    align-items: center;
Убрал. Оставил в этом медиа-запросе только 
  .form,
  .form_style {
    flex-direction: column;
    align-items: normal;
  }

2023-08-18 03:15 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    display: flex;
убрал

2023-08-18 09:34 UTC, foxprogs commented on subscribe_card/styles.css
> +  font: 500 0.9rem "Roboto", sans-serif;
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/0d22c5d3-7ce8-4956-bb79-0fdc4aaca2c0)
@Yuriy2437 изменений нет. Или забыли закоммитить.

2023-08-18 09:41 UTC, foxprogs commented on subscribe_card/styles.css
> +  color: #3d5603;
он же не меняется. Для чего тогда его тут указывать.

2023-08-18 09:47 UTC, foxprogs commented on subscribe_card/styles.css
> +.btn:active {
И мне кажется что сейчас те же цвета что были в прошлый раз. Я тогда писал что слишком темные ховер и эктив. На примере видно что изменения не такие заметные. Есть еще такой параметр как контрастность. Цвет текста и фона должны быть достаточно контрастными чтобы их можно было прочесть. 
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/c080b27a-4c6d-4869-a4e0-17168baaddd3)

Тут на скрине видно (в окне выбора цвета внизу слева красный круг с "!" знаком) что контрастность 1.76. Это плохо читаемо. Вообще хорошим считается значение 4,5.

2023-08-18 09:51 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  font: 500 0.9rem "Roboto", sans-serif;
Прошу прощения. Закоммитил  font: 500 0.9rem/1.6 "Roboto", sans-serif;

2023-08-18 09:54 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  color: #3d5603;
Убрал дважды дубляж цвета текста в кнопке по наведению и нажатию

2023-08-18 10:13 UTC, foxprogs reviewed
нужны еще несколько исправлений

2023-08-18 10:18 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  }
Это флекс-элементы. display: flex передается им из .form {
  display: flex; в строке 54-55 вне медиа-запроса. Эти стили нужны, чтобы обеспечить вертикальное (колоночное), а не горизонтальное позиционирование в медиазапросе @media (max-width: 499px)

2023-08-18 10:22 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +.btn:active {
хорошо, подумаю, как сделать контрастнее

2023-08-18 10:41 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +  }
Извините, не понял сразу суть вашего замечания. Оставил здесь form и убрал form_style

2023-08-18 12:01 UTC, Yuriy2437 commented on subscribe_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/248798887-21bf58b0-121d-4b12-83aa-b476992a5cb5.png" class="btn btn_style">Subscribe</a>
Сделаны четкие контрасты по hover и active

2023-08-18 12:03 UTC, Yuriy2437 commented on subscribe_card/styles.css
> +    display: flex;
убрал form_style, оставил только form

2023-08-19 12:14 UTC, foxprogs approved these changes

2023-08-19 22:11 UTC, merged