Menu Block
tt-dev-23/Yuriy2437_Practice pull request #11
Opened 2023-08-20 16:27 UTC by Yuriy2437

Верстка блока меню, #6

2023-08-21 06:26 UTC, foxprogs commented on menu_block/index.html
> +        </div>
это не table а menu. И надо его переверстать. тут два блока, в каждом блоке заголовок и пункты меню.

2023-08-21 06:30 UTC, foxprogs commented on menu_block/index.html
> +              <h5 class="text">
можно удалить класс text. Можно обратиться по `.text_part h5`
Тут еще такая проблема, что название очень общее. Я бы классы title и text удалил

2023-08-21 14:51 UTC, Yuriy2437 commented on menu_block/index.html
> +              <h5 class="text">
Удалил классы title и text

2023-08-21 14:57 UTC, Yuriy2437 commented on menu_block/index.html
> +        </div>
Переверстал на два блока, изменил названия классов

2023-08-21 15:58 UTC, foxprogs commented on menu_block/styles.css
> +  height: 19.375rem;
замечания такие же как и в прошлых заданиях. Высоту надо убрать. И отступы прописаны не у тех элементов. Тут должен быть пэддинг 1.3. А он, вместо одного места, указан как мэрджин у notification и у blocks.block

2023-08-21 16:16 UTC, foxprogs commented
![image](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/eb314620-a17c-4bd8-ad79-b59147056e4a)
надо сразу мобильную версию делать. Вот пример как я сделал.

2023-08-21 16:17 UTC, foxprogs commented on menu_block/styles.css
> +  margin: 1.8rem 1rem 0.6rem 0;
это тоже надо удалить. Выровнять очень просто через флекс

2023-08-21 16:18 UTC, foxprogs commented on menu_block/styles.css
> +  grid-template-columns: repeat(2, 13rem);
13rem надо заменить на 1fr. я уже много раз в тех заданиях писал что мы не делаем фиксированный дизайн, надо его делать гибким и минимально привязываться к каким-то точным размерам.

2023-08-21 16:20 UTC, foxprogs commented on menu_block/styles.css
> +  margin: -0.5rem;
не, так не надо. Надо просто посмотреть на дизайн и понять, где наш блок. Сейчас отступы сделаны через gap. По этому тут приходится как-то выкручиваться. А по дизайну видно что row принадлежит отступ вокруг. Это должно быть padding у row

2023-08-21 16:21 UTC, foxprogs requested changes
надо стили переписать, чтобы был гибкий дизайн

2023-08-22 12:03 UTC, Yuriy2437 commented on menu_block/styles.css
> +  height: 19.375rem;
убрал высоту, сделал padding: 1.3rem; в card, убрал margin: 1.3rem 1.3rem 0 1.3rem; из notification, уменьшил margin-left в block на 1.3rem, до 0.7rem

2023-08-22 12:09 UTC, Yuriy2437 commented on menu_block/styles.css
> +  padding: 0 0 0 1rem;
Убрал из notification margin: 1.3rem 1.3rem 0 1.3rem; добавил в notification padding: 0.75rem 1rem 0.75rem 1rem; убрал из text_part  margin: 1rem 0;

2023-08-22 12:18 UTC, Yuriy2437 commented on menu_block/styles.css
> +  margin: 1.8rem 1rem 0.6rem 0;
Удалил. В классе content поставил align-items: flex-end;

2023-08-22 12:24 UTC, Yuriy2437 commented on menu_block/styles.css
> +  grid-template-columns: repeat(2, 13rem);
заменил

2023-08-22 14:28 UTC, Yuriy2437 commented
> ![image](https://user-images.githubusercontent.com/30548361/262083068-eb314620-a17c-4bd8-ad79-b59147056e4a.png) надо сразу мобильную версию делать. Вот пример как я сделал.

Реализована мобильная версия

2023-08-22 23:24 UTC, foxprogs commented on menu_block/styles.css
> +  padding: 0 0 0 1rem;
тут у меня комментарий не к 28 строке же, а к 29

2023-08-22 23:28 UTC, foxprogs commented
Нужно привести к дизайну. 
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/758bdc5b-493d-4be8-9922-3371e6d8bc29)
Заголовки сейчас сильно прижаты, при ховере нет pointer и подсвечивается блок не так как в дизайне
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/f4ed3b07-a138-4253-b7cd-8a4684afd398)
кнопка прижимается к тексту

2023-08-22 23:29 UTC, foxprogs commented on menu_block/index.html
> +                Latest on technology, documentation <br />
br надо убрать, без него можно сверстать

2023-08-22 23:31 UTC, foxprogs commented on menu_block/index.html
> +          <div class="content">
для чего в notification лежит блок content. Он никакой нагрузки не несет, его можно упразднить

2023-08-22 23:33 UTC, foxprogs commented on menu_block/styles.css
> +  flex-direction: column;
разве тут нужен флекс? там же просто идет текст друг под другом

2023-08-22 23:34 UTC, foxprogs commented on menu_block/styles.css
> +}
для чего один и тот же код писать два раза?

2023-08-22 23:34 UTC, foxprogs commented on menu_block/styles.css
> +}
можно либо указать все у родителя, либо через запятую указать несколько селекторов

2023-08-22 23:42 UTC, Yuriy2437 commented on menu_block/styles.css
> +}
Объединил text_part h3, text_part h5

2023-08-22 23:45 UTC, Yuriy2437 commented on menu_block/styles.css
> +  flex-direction: column;
убрал

2023-08-22 23:48 UTC, Yuriy2437 commented on menu_block/index.html
> +          <div class="content">
Content соединяет флексом текстовую часть и кнопку: вот этим кодом .content {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
}

2023-08-22 23:52 UTC, Yuriy2437 commented on menu_block/index.html
> +                Latest on technology, documentation <br />
но текст тогда наползает на кнопку...ломается структура

2023-08-23 00:00 UTC, Yuriy2437 commented on menu_block/styles.css
> +  padding: 0 0 0 1rem;
padding: 1rem сделан в блоке notification; padding: 0 0 0 1rem убран

2023-08-28 10:09 UTC, Yuriy2437 commented on menu_block/index.html
> +          <div class="content">
Убран класс content. Флексы вставлены в класс notification

2023-08-28 11:16 UTC, Yuriy2437 commented on menu_block/index.html
> +                Latest on technology, documentation <br />
Осуществлен перенос строки другим способом, без использования br

2023-08-28 12:36 UTC, Yuriy2437 commented
> Нужно привести к дизайну. ![изображение](https://user-images.githubusercontent.com/30548361/262504934-758bdc5b-493d-4be8-9922-3371e6d8bc29.png) Заголовки сейчас сильно прижаты, при ховере нет pointer и подсвечивается блок не так как в дизайне ![изображение](https://user-images.githubusercontent.com/30548361/262505058-f4ed3b07-a138-4253-b7cd-8a4684afd398.png) кнопка прижимается к тексту

Приведено к дизайну. Исправлено.

2023-08-28 15:45 UTC, foxprogs commented on menu_block/index.html
> +            <h5>Latest on technology, documentation <span>and code examples</span></h5>
не, это хак. Допустим у нас на сайте будут 3 блока меню. У них будет разный контент, разное наполнение. И пользователь должен будет прописывать спаны или переносы строки? Ну скорее всего нет, по этому это надо сделать стилями. Делается достаточно просто, уже подобный код был.
1 - использовать gap для того чтобы между блоком с текстом и кнопкой точно был отступ и она не наплывала друг на друга. Тогда не важно сколько контента, какая ширина этого блока будет - всегда будет все смотреться отлично. 
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/69de8def-de7f-4526-b73e-5b0034ac68e8)
2. У кнопки надо приминить flex, чтобы текст в кнопке не переносился в 2 строки и чтобы кнопка занимала ровно свою ширину

2023-08-28 15:48 UTC, foxprogs commented on menu_block/index.html
> +      <div class="card">
у карточки не хватает margin вокруг, если удалить ширину, то он при определенном размере прижимается к краю окна
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/523c1287-ee9c-486c-8f2c-2507b53fb8a4)
вот то как выглядит сейчас если убрать фикс размер

2023-08-28 17:37 UTC, foxprogs reviewed
оставил замечания по коду

2023-08-28 21:57 UTC, Yuriy2437 commented on menu_block/index.html
> +            <h5>Latest on technology, documentation <span>and code examples</span></h5>
Убрал br и span. Сделал gap: 3rem у notification, а также  white-space: nowrap у кнопки

2023-08-28 22:00 UTC, Yuriy2437 commented on menu_block/index.html
> +      <div class="card">
Сделал у card margin: 1rem, убрал фиксированную ширину

2023-08-28 22:07 UTC, Yuriy2437 commented on menu_block/styles.css
> +  width: 26.875rem;
Сделал max-width: 50rem. Если же убрать медиа-запрос, то на ширине менее 300px происходит выход card за границы диапазона. Все равно убирать?

2023-08-29 13:11 UTC, foxprogs commented on menu_block/styles.css
> +  width: 26.875rem;
я сделал комментарий к 18 строке только, и указал что именно тут не надо будет использовать медиа запрос) речь не шла о том чтобы все запросы убрать.
тут указана фикс ширина, которая потом медиа запросом перебивается. Я и написал, что можно сделать сразу и отступ и ширину удобной, чтобы ничего не перебивать. 
Меню в одну колонку надо вернуть, мы не знаем какие там будут пункты и заголовки. Может и короткие, может и длинные.

2023-08-29 13:16 UTC, foxprogs commented on menu_block/index.html
> +            <h5>Latest on technology, documentation and code examples</h5>
вот этот текст не жирным же написан, а font-weight: 400

2023-08-29 13:56 UTC, foxprogs commented on menu_block/styles.css
> +  gap: 0.7rem;
я бы делал 1.2 минимум. Как сейчас - по ощущениям кажется очень близко

2023-08-29 13:57 UTC, foxprogs reviewed
есть пару комментариев, и надо вернуть мобильную версию, какая была раньше

2023-08-29 15:43 UTC, Yuriy2437 commented on menu_block/styles.css
> +  width: 26.875rem;
Вернул медиа-запрос, только в сильно сокращенном виде, для одной колонки в блоках. Остальной код мне видится здесь лишним: 
@media (max-width: 499px) {
  .blocks {
    grid-template-columns: auto;
  }
}

2023-08-29 15:50 UTC, Yuriy2437 commented on menu_block/index.html
> +            <h5>Latest on technology, documentation and code examples</h5>
Исправлено

2023-08-29 17:46 UTC, Yuriy2437 commented on menu_block/styles.css
> +  width: 26.875rem;
Изменил дизайн медиа-запроса, чтобы текст занимал максимум ширины notification, и кнопка была во всю ширину

2023-08-30 06:55 UTC, foxprogs commented on menu_block/styles.css
> +  display: grid;
а для чего тут грид?

2023-08-30 06:58 UTC, foxprogs commented on menu_block/styles.css
> +    align-self: stretch;
либо можно эти 4 свойства заменить на два
```css
width: 100%;
text-align: center;
```

2023-08-30 06:58 UTC, foxprogs reviewed
Вроде теперь все хорошо. Только 2 комментария

2023-08-30 07:48 UTC, Yuriy2437 commented on menu_block/styles.css
> +  display: grid;
убрал

2023-08-30 07:54 UTC, Yuriy2437 commented on menu_block/styles.css
> +    align-self: stretch;
заменил

2023-08-30 08:02 UTC, foxprogs approved these changes

2023-08-30 08:07 UTC, merged