Исправление задачи по issue 1, Pricing Card
tt-dev-23/Yuriy2437_Practice pull request #3
Opened 2023-06-19 19:52 UTC by Yuriy2437

Создаем пулреквест для ветки 1

2023-06-19 20:29 UTC, foxprogs commented on pricing_card/index.html
> +    <div class="container" onclick="window.open('https://user-images.githubusercontent.com/30548361/245472231-5556604b-74eb-4abe-9530-eb6a8880a32c.png')">
onclick тут не нужен. Достаточно клика по кнопке

2023-06-19 20:31 UTC, foxprogs commented on pricing_card/index.html
> +        <div class="black-square">
надо придерживаться одного стиля именования классов. Или через дефис или через нижнее подчеркивание

2023-06-19 20:36 UTC, foxprogs commented on pricing_card/index.html
> +        <div class="black-square">
Второй момент - это сами имена классов. Лучше именовать их по их значению чем по цвету. Завтра поменяется у карточки фон, вместо синего будет оранжевый и придется менять все имена классов.
 Лучше тут подойти так
```
card
  header
    logo
    title
  content
```
Это компонент карточки, и если цвета у будущем поменяются - ничего не придется переписывать

2023-06-19 20:37 UTC, foxprogs commented on pricing_card/index.html
> +        <div class="photoshop">
тут тоже самое с именами классов. И дальше, везде надо подправить

2023-06-19 20:38 UTC, foxprogs commented on pricing_card/index.html
> +        <a href="https://user-images.githubusercontent.com/30548361/245472231-5556604b-74eb-4abe-9530-eb6a8880a32c.png" class="btn">Buy Now </a>
пробел после `Now ` не нужен

2023-06-19 20:41 UTC, foxprogs commented on pricing_card/styles.css
> +  cursor: pointer;
это тоже не надо. Сейчас кликабельно вообще все окно. А по идее должна только кнопка и ссылка

2023-06-19 20:51 UTC, foxprogs commented on pricing_card/index.html
> +      <div class="blue_rectangle">
не хватает класса card в котором будет карточка назодиться

2023-06-19 20:52 UTC, foxprogs commented on pricing_card/styles.css
> +  border: 1px solid #153c63;
для чего этот бордер?

2023-06-19 20:53 UTC, foxprogs commented on pricing_card/styles.css
> +  background-color: #000;
надо делать максимально как на картинке. Там нет черного цвета.

2023-06-19 20:54 UTC, foxprogs commented on pricing_card/styles.css
> +  font-family: sans-serif;
шрифт не надо писать в каждом блоке. Его надо просто один раз у родителя указать и все

2023-06-19 20:54 UTC, foxprogs commented on pricing_card/styles.css
> +  font-family: sans-serif;
Шрифт который сейчас - не похож. Надо найти подходящий например тут https://fonts.google.com/ и добавить его

2023-06-19 20:57 UTC, foxprogs commented on pricing_card/styles.css
> +}
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/76e51b7b-a831-4d74-bfb0-65e14d39db1a)
такое выравнивание это очень плохая практика

2023-06-19 20:59 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-right: 65px;
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/2fdf37b5-3f6c-449e-9998-268b573719e7)
почему такой неровный отступ?

2023-06-19 21:00 UTC, foxprogs commented on pricing_card/styles.css
> +  font-size: 15px;
почему тут пиксели а ниже em? Надо писать все в одном стиле, и лучше использовать относительные величины

2023-06-19 21:04 UTC, foxprogs commented on pricing_card/styles.css
> +  color: rgb(6, 181, 234);
лучше везде в одном стиле цвета испоьзовать. Если hex то так и дальше делать

2023-06-19 21:15 UTC, foxprogs commented on pricing_card/styles.css
> +  height: 100px;
надо сделать без высоты

2023-06-19 21:16 UTC, foxprogs commented on pricing_card/styles.css
> +  width: 350px;
ширину тоже убрать, сделать класс родитель `card` и ему уже указать ширину

2023-06-19 21:16 UTC, foxprogs commented on pricing_card/styles.css
> +  height: 300px;
это тоже убрать

2023-06-19 21:16 UTC, foxprogs commented on pricing_card/styles.css
> +  height: 300px;
высота карточки будет склаываться из контента который в нем. Если его много - она будет больше, если мало то меньше

2023-06-19 21:17 UTC, foxprogs commented on pricing_card/styles.css
> +  position: relative;
нужна веская причина чтобы выравнивать через позишн.

2023-06-19 21:18 UTC, foxprogs commented on pricing_card/styles.css
> +  left: 25px;
это надо убрать. Нам надо верстать адаптивный дизайн. По этому используем относительные величины вместо абсолютных, используем display:flex

2023-06-19 21:19 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-top: 30px;
почему только слева и сверху? Если у нас появится вторая карточка где будет немного больше текста, то он будет смотреттся криво так как прижмется к правому краю, оттуда же нет отступа

2023-06-19 21:20 UTC, foxprogs commented on pricing_card/styles.css
> +  line-height: 1.5;
для чего тут этот стиль

2023-06-19 21:26 UTC, foxprogs commented on pricing_card/index.html
> +          <p>Photoshop</p>
можно тег параграфа и не использовать

2023-06-19 21:36 UTC, foxprogs commented on pricing_card/index.html
> +    <link href="styles.css" rel="stylesheet" />
нехватает сброса стилей, нужно подключить его до стилей страницы

2023-06-19 21:46 UTC, foxprogs requested changes
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/2de311e8-4c4d-4cf7-ba8c-5fa1ae8896e2)
Слева то как получилось у меня. Вот надо постараться чтобы получилось лучше. Тут видно что я цвет фона не совсем тот указал, цвет основного текста надо чуть поменять

2023-06-19 21:52 UTC, foxprogs commented on pricing_card/styles.css
> +  padding: 10px 100px;
padding 100 это плохо. К примеру вы переведем текст, и тут будет не Buy now а "Оформить Заказ". И получается такая красота 
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/8dc51ca2-d0c2-4ca5-afd4-bfc46b35e091)

2023-06-19 21:55 UTC, foxprogs commented on pricing_card/styles.css
> +  padding: 10px 100px;
на много лучше будет если сделать ссылку display:block

2023-06-19 21:56 UTC, foxprogs commented on pricing_card/styles.css
> +  height: 300px;
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/6ed527d9-18ce-4e89-a458-4103280b63d2)
вот что будет если добавить текста к примеру

2023-06-21 21:49 UTC, foxprogs commented on pricing_card/styles.css
> +}
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/7cf89075-f8ce-4dbe-b716-cd2945c5650a)
убрать position, сделать через флексы

2023-06-21 21:51 UTC, foxprogs commented on pricing_card/styles.css
> +  position: relative;
position: relative; надо убрать

2023-06-21 21:59 UTC, foxprogs commented on pricing_card/styles.css
> +  background-color: #0c013f;
#001e36

2023-06-21 21:59 UTC, foxprogs commented on pricing_card/styles.css
> +  color: #07b4e8;
#31a8ff

2023-06-21 22:00 UTC, foxprogs commented on pricing_card/index.html
> +            <span>Photoshop</span>
этот тоже

2023-06-21 22:01 UTC, foxprogs commented on pricing_card/index.html
> +          <div class="btn-container">
этот див убрать

2023-06-21 22:01 UTC, foxprogs commented on pricing_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/245472231-5556604b-74eb-4abe-9530-eb6a8880a32c.png" class="btn"><span>Buy Now</span></a>
спан внутри убрать

2023-06-21 22:02 UTC, foxprogs commented on pricing_card/styles.css
> +  transform: translate(50%, 50%);
Это зачем?

2023-06-21 22:02 UTC, foxprogs commented on pricing_card/styles.css
> +  transform: translateX(30%);
Это зачем? надо убрать

2023-06-21 22:02 UTC, foxprogs commented on pricing_card/styles.css
> +  color: white;
все цвета переписать в hex формате

2023-06-21 22:03 UTC, foxprogs commented on pricing_card/styles.css
> +  border-radius: 10px 10px 0 0;
вместо двух радиусов его можно один раз применить для .card

2023-06-21 22:04 UTC, foxprogs commented on pricing_card/styles.css
> +  min-height: 100px;
это для чего?

2023-06-21 22:08 UTC, foxprogs commented on pricing_card/styles.css
> +  background-color: #f3fbfb;
#f5f9ff

2023-06-21 22:09 UTC, foxprogs commented on pricing_card/styles.css
> +  background-color: #153c63;
#133e61

2023-06-21 22:09 UTC, foxprogs commented on pricing_card/styles.css
> +  background: #153c63;
#133e61

2023-06-21 22:12 UTC, foxprogs commented on pricing_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/245472231-5556604b-74eb-4abe-9530-eb6a8880a32c.png" class="btn"><span>Buy Now</span></a>
now c маленькой буквы

2023-06-21 22:15 UTC, foxprogs requested changes
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/bb71d679-a696-4c5f-ab6e-39cb9a2093a3)
цвет ссылки, лого, расстояние между строк в тексте, отступы сверху и снизу - это то что бросается в глаза, надо исправить.

2023-06-21 22:18 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-bottom: 30px;
почему margin?

2023-06-21 22:18 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-top: 0;
для чего это?

2023-06-21 22:19 UTC, foxprogs commented on pricing_card/styles.css
> +  margin: 0;
для чего это?

2023-06-21 22:19 UTC, foxprogs commented on pricing_card/styles.css
> +  bottom: 15px;
для чего это?

2023-06-21 22:20 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-right: 47px;
можно записать margin: 0 47px;

2023-06-21 22:20 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-left: 47px;
почему только слева?

2023-06-21 22:21 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-right: 47px;
раз он везде повторяется, почему его не указать один раз у .content

2023-06-21 22:22 UTC, foxprogs commented on pricing_card/styles.css
> +  justify-content: center;
что это?

2023-06-21 22:22 UTC, foxprogs commented on pricing_card/styles.css
> +  cursor: pointer;
зачем это?

2023-06-21 22:23 UTC, foxprogs reviewed
еще вопросы по поводу стилей, для чего они указаны?

2023-06-22 20:11 UTC, Yuriy2437 commented on pricing_card/styles.css
> +}
уже убраны position, были в первой версии

2023-06-22 20:11 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  position: relative;
уже убраны, были в первой версии

2023-06-22 20:12 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  background-color: #0c013f;
исправил

2023-06-22 20:12 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  color: #07b4e8;
исправил

2023-06-22 20:13 UTC, Yuriy2437 commented on pricing_card/index.html
> +            <span>Ps</span>
убрал

2023-06-22 20:13 UTC, Yuriy2437 commented on pricing_card/index.html
> +            <span>Photoshop</span>
убрал

2023-06-22 20:13 UTC, Yuriy2437 commented on pricing_card/index.html
> +          <div class="btn-container">
убрал

2023-06-22 20:14 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  transform: translate(50%, 50%);
Этот код нужен для: а) переноса logo в центральную часть header, равноудаленную от верхнего, левого и нижнего края; б) для центрирования текста Ps внутри logo

2023-06-22 20:15 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  transform: translateX(30%);
В этом коде три строки после display: flex центрируют надпись Photoshop в header. А строка transform перемещает его по оси Х в нужную сторону на необходимое расстояние

2023-06-22 20:15 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  color: white;
сделал

2023-06-22 20:16 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  border-radius: 10px 10px 0 0;
Это не получается. Класс .card не реагирует на скругления, а его подклассы реагируют.

2023-06-22 20:17 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  min-height: 100px;
убрал, заменил на height

2023-06-22 20:17 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  background-color: #f3fbfb;
изменил

2023-06-22 20:17 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  background-color: #153c63;
изменил

2023-06-22 20:18 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  background: #153c63;
изменил

2023-06-22 20:18 UTC, Yuriy2437 commented on pricing_card/index.html
> +            <a href="https://user-images.githubusercontent.com/30548361/245472231-5556604b-74eb-4abe-9530-eb6a8880a32c.png" class="btn"><span>Buy Now</span></a>
изменил

2023-06-22 20:19 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  margin-bottom: 30px;
Свойство найдено экспериментальным путем. Именно margin-bottom: 30px обеспечивает идеальное центрирование квадрата logo в header.

2023-06-22 20:20 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  margin-top: 0;
удалил

2023-06-22 20:20 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  margin: 0;
удалил

2023-06-22 20:21 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  margin-right: 47px;
перенес в класс content

2023-06-22 20:22 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  margin-left: 47px;
перенес в класс content, там и слева, и справа

2023-06-22 20:22 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  margin-right: 47px;
указал в content

2023-06-22 20:26 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  cursor: pointer;
Если вопрос насчет курсора, то для нажатия кнопки и перехода. Или я не понял вопрос...

2023-06-23 06:53 UTC, foxprogs commented on pricing_card/styles.css
> +  cursor: pointer;
@Yuriy2437 просто это же ссылка, тег `<a>`, у него по умолчанию курсор поинтер

2023-06-23 06:53 UTC, foxprogs commented on pricing_card/styles.css
> +  cursor: pointer;
по этому это лишнее, можно убрать

2023-06-23 06:58 UTC, foxprogs commented on pricing_card/styles.css
> +  border-radius: 10px 10px 0 0;
почему не получится? Мы так уже делали в прошлый раз по практике css
```css
border-radius: 10px;
overflow: hidden;
```

2023-06-23 07:01 UTC, foxprogs commented on pricing_card/index.html
> +          <div class="logo"></div>
Текст надо вернуть, должно быть 
```html
<div class="logo">Ps</div>
<div class="inscription">Photoshop</div>
```

2023-06-23 07:06 UTC, foxprogs commented on pricing_card/index.html
> +          <p class="reference">
надо удалить этот параграф тоже. Просто добавить класс к ссылке
`<a class="reference" href="https://user-images.githubusercontent.com/30548361/245472231-5556604b-74eb-4abe-9530-eb6a8880a32c.png">Plan & pricing details</a>`
а для класса reference в стилях добавить `display: block`

2023-06-23 07:07 UTC, foxprogs commented on pricing_card/styles.css
> +  width: 290px;
а почему раньше был 350 а теперь 290?

2023-06-23 07:08 UTC, foxprogs commented on pricing_card/styles.css
> +  height: 98px;
убрать совсем

2023-06-23 07:08 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-bottom: 30px;
удалить. Это свойство надо применять так как тут остальное сверстано не правильно

2023-06-23 07:09 UTC, foxprogs commented on pricing_card/styles.css
> +  position: relative;
почему? Оно сейчас есть до сих пор. Надо убрать

2023-06-23 07:10 UTC, foxprogs commented on pricing_card/styles.css
> +  padding-right: 34px;
я уже писал в прошлый раз, чтобы не записывать два свойства можно написать просто `padding: 0px 34px`

2023-06-23 07:20 UTC, foxprogs commented on pricing_card/styles.css
> +  transform: translate(50%, 50%);
Надо удалить. Это избыточный код, текст внутри лого через transform не выравнивается.

2023-06-23 07:22 UTC, foxprogs commented on pricing_card/styles.css
> +  transform: translate(50%, 50%);
два блока внутри header выравниваются очень просто через `flex` и `justify-content: space-between` к примеру

2023-06-23 07:22 UTC, foxprogs commented on pricing_card/styles.css
> +}
это все удалить, цвет и шрифт можно просто добавить в класс logo и все

2023-06-23 07:23 UTC, foxprogs commented on pricing_card/styles.css
> +  transform: translateX(30%);
трансформом не надо ничего позиционировать, это тут лишнее. надо удалить

2023-06-23 07:24 UTC, foxprogs commented on pricing_card/styles.css
> +}
это все удалить, стиль для текста перенести в inscription

2023-06-23 07:24 UTC, foxprogs commented on pricing_card/styles.css
> +  border-top-color: #fff;
Что это?

2023-06-23 07:25 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-bottom: 0.1em;
почему сверху пэддинг а снизу мэрджин?

2023-06-23 07:27 UTC, foxprogs commented on pricing_card/styles.css
> +  bottom: 32px;
это надо удалить

2023-06-23 07:27 UTC, foxprogs reviewed
Надо удалить все неправильные стили и исправить

2023-06-23 07:38 UTC, foxprogs commented on pricing_card/styles.css
> +  padding-right: 34px;
и почему отступ только слева и справа? В дизайне еще сверху и снизу

2023-06-23 07:39 UTC, foxprogs commented on pricing_card/styles.css
> +}
из за transform этот блок где-то в стороне

2023-06-23 07:40 UTC, foxprogs commented on pricing_card/index.html
> +            <span>Ps</span>
Я написал убрать тег, но текст надо было оставить

2023-06-23 07:40 UTC, foxprogs commented on pricing_card/index.html
> +            <span>Photoshop</span>
текст надо было оставить

2023-06-23 07:41 UTC, foxprogs commented on pricing_card/styles.css
> +  min-height: 100px;
для чего фиксированная высота? Надо убрать, просто добавить внутри шапки отступы и все

2023-06-23 07:44 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-right: 47px;
там где можно - используем сокращенную запись

2023-06-23 07:45 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-bottom: 0.1em;
вопрос, в чем отличие margin и padding. Когда применять одно а когда второе?

2023-06-23 18:34 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  border-radius: 10px 10px 0 0;
В этом варианте у меня создается скругление только шапки, но не белого контента

2023-06-23 18:39 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  transform: translate(50%, 50%);
убрал трансформ

2023-06-23 18:40 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  transform: translateX(30%);
убрал трансформ

2023-06-23 18:46 UTC, Yuriy2437 commented on pricing_card/index.html
> +            <span>Ps</span>
Возникает проблема: если оставить текст, и убрать content: "Ps", то не работают свойства logo::before. Если оставить текст и не убирать content: "Ps", то текст Ps удваивается. Что делать?

2023-06-23 18:48 UTC, Yuriy2437 commented on pricing_card/index.html
> +            <span>Photoshop</span>
Возникает проблема: если оставить текст, и убрать content: "Photoshop", то не работают свойства inscription::before. Если оставить текст и не убирать content: "Photoshop", то текст Photoshop удваивается. Что делать?

2023-06-23 18:52 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  min-height: 100px;
убрал

2023-06-23 18:54 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  cursor: pointer;
убрал

2023-06-23 18:58 UTC, Yuriy2437 commented on pricing_card/index.html
> +          <div class="logo"></div>
Выше я уже писал, что при возвращении текста в этом варианте получается конфликт: 
1)Возникает проблема: если оставить текст, и убрать content: "Photoshop", то не работают свойства inscription::before. Если оставить текст и не убирать content: "Photoshop", то текст Photoshop удваивается. Что делать?
2) Возникает проблема: если оставить текст, и убрать content: "Ps", то не работают свойства logo::before. Если оставить текст и не убирать content: "Ps", то текст Ps удваивается. Что делать?

2023-06-23 19:01 UTC, Yuriy2437 commented on pricing_card/index.html
> +          <p class="reference">
выполнено

2023-06-23 19:02 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  width: 290px;
чтобы точнее соответствовать параметрам оригинального дизайна карточки

2023-06-23 19:03 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  height: 98px;
убрал

2023-06-23 19:07 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  padding-right: 34px;
добавил снизу, сверху если добавить, сломается структура внешнего вида

2023-06-23 19:11 UTC, Yuriy2437 commented on pricing_card/styles.css
> +}
Удалил. Добавил. Вернул Ps и Photoshop в div.

2023-06-23 19:12 UTC, Yuriy2437 commented on pricing_card/index.html
> +          <div class="logo"></div>
Приношу извинения. Ошибся. Вернул Ps и Photoshop в div. Удалил inscription::before и logo::before.

2023-06-23 19:13 UTC, Yuriy2437 commented on pricing_card/index.html
> +            <span>Photoshop</span>
Приношу извинения. Ошибся. Вернул Ps и Photoshop в div. Удалил inscription::before и logo::before.

2023-06-23 19:13 UTC, Yuriy2437 commented on pricing_card/index.html
> +            <span>Ps</span>
Приношу извинения. Ошибся. Вернул Ps и Photoshop в div. Удалил inscription::before и logo::before.

2023-06-23 19:14 UTC, Yuriy2437 commented on pricing_card/styles.css
> +}
Удалил. Добавил. Вернул Ps и Photoshop в div.

2023-06-23 19:17 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  border-top-color: #fff;
Ошибся. Убрал.

2023-06-23 19:49 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  margin-bottom: 0.1em;
Убрал padding. Вместо него теперь padding-bottom в контенте. 
Насколько я понял, padding - это внутренний отступ, внутри элемента, между границей элемента и его содержимым. Он не меняет размер самого элемента. Margin, внешний отступ, добавляется за пределы границы элемента, создает промежутки между элементами, сдвигает их по отношению друг к другу.
То есть, margin надо ставить, когда нужно создать промежутки между элементами. А padding - когда создать пространство внутри элемента, между содержимым и границей.

Это - в теории. А на практике здесь с помощью margin-bottom: 0.1em уменьшается пространство между title и text для точности дизайна.

2023-06-23 19:50 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  bottom: 32px;
удалил

2023-06-25 14:00 UTC, foxprogs commented on pricing_card/styles.css
> +  border-radius: 10px 10px 0 0;
я уже несколько раз писал. Проблема в том что тут куча неправильных стилей. Если посмотреть в инспекторе, то там все скругляется но почему-то у контента указан position, про который я уже много раз написал, что его надо удалить. Он поднимает контент и в итоге скругления не видео, это первое. А второе - контент заплывает на шапку.

2023-06-25 14:01 UTC, foxprogs commented on pricing_card/styles.css
> +  position: relative;
Пишу еще раз, надо убрать этот стиль @Yuriy2437

2023-06-25 14:01 UTC, foxprogs commented on pricing_card/styles.css
> +  padding-bottom: 53px;
третий раз пишу про то что надо использовать сокращенный вариант, а не три раза padding-*

2023-06-25 14:08 UTC, foxprogs commented on pricing_card/styles.css
> +  padding-right: 34px;
ломается из за неправильных стилей, в частности position relative. Отступ сверху должен быть просто по логике вещей, исходя из дизайна. Просто любой другой контент если в карточке разместить, отступ же все равно будет вокруг? А если его не делать, то придется тогда этот отступ делать у того что будет первым в карточке. Сейчас типа заголовка, а где-то будет контент, или картинка

2023-06-25 14:13 UTC, foxprogs commented on pricing_card/styles.css
> +.content {
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/abb216e1-4eff-418b-8950-8ffa41c8831e)
вот так сейчас выглядит этот блок. И это не правильно. Почему отступ снизу такой большой и наплывает на контент? Почему отступа справа нет?

2023-06-25 14:18 UTC, foxprogs commented on pricing_card/styles.css
> +  align-items: flex-end;
можно к header добавить к примеру align-items: baseline;

2023-06-25 14:53 UTC, foxprogs commented on pricing_card/styles.css
> +  padding-bottom: 53px;
и я так понимаю что 53 получилось, потому что удалили margin 30 и эти 30 добавили к пэддингу?

2023-06-25 14:58 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-right: 47px;
@Yuriy2437 снова повторю про сокращенную запись https://yoksel.github.io/easy-css/shorthand-properties/

2023-06-25 15:12 UTC, foxprogs commented on pricing_card/styles.css
> +  margin-bottom: 0.1em;
да, теперь я понял в чем проблема. Есть два подхода к тому чтобы привести стиль элементов к одному во всех браузерах. Это сброс и нормализация. Возьмем к примеру заголовок h1. Сброс уберет все отступы и размер шрифта, он будет похож на текст параграфа. А вот нормализация сделает его большим шрифтом и добавит отступы сверху и снизу. Тут применена нормализация ко всей странице, по этому и приходится перебивать эти стили. У параграфа тоже к примеру сейчас есть какие-то отступы. В будущем лучше применять именно сброс а не нормализацию. Чтобы самому все отступы и размеры указывать.

2023-06-25 15:13 UTC, foxprogs commented on pricing_card/styles.css
> +  position: relative;
для чего вот это?

2023-06-25 15:14 UTC, foxprogs commented on pricing_card/styles.css
> +  bottom: 32px;
нет, тут так и остался position

2023-06-25 15:17 UTC, foxprogs reviewed
остались еще непрвильные стили, надо исправить

2023-06-26 07:23 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  position: relative;
Пожалуйста, посмотрите, текст файла styles.css. Этот стиля там давно нет.

2023-06-26 07:30 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  position: relative;
Аааа...понял...дело в position. Прошу прощения. Убрал.

2023-06-26 08:07 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  margin-right: 47px;
Дважды использовал сокращенную запись для padding

2023-06-26 08:17 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  padding-right: 34px;
Теперь контент не ломается, убрал position, изменил padding, теперь можно убрать bottom 30px

2023-06-26 08:22 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  bottom: 32px;
Убрал position из btn

2023-06-26 08:53 UTC, Yuriy2437 commented on pricing_card/styles.css
> +.content {
В новой версии header'a там все ровно и таких отступов нет

2023-06-26 09:03 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  align-items: flex-end;
Добавил. Хотя, не увидел, что это изменило. Просмотрел код header, все так же.

2023-06-26 09:03 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  padding-bottom: 53px;
уже изменил, теперь 23

2023-06-26 09:26 UTC, foxprogs commented on pricing_card/styles.css
> +.content {
@Yuriy2437 второй вопрос так и остался, "Почему отступа справа нет?" Он тут по логике вещей просится. А сейчас отступ справа почему-то реализован через `margin-right` у `inscription`. Надо исправить

2023-06-26 09:50 UTC, foxprogs commented on pricing_card/styles.css
> +  padding: 23px 0 23px 23px;
тут надо просто сделать padding: 23px и подправить стиль у Photoshop

2023-06-26 09:56 UTC, foxprogs commented on pricing_card/styles.css
> +  padding: 0 34px 32px;
я понимаю что там у h1 по умолчанию margin сверху, но все равно по дизайну видно что есть блок контент и внутри него все содержимое. И отступы относятся именно к блоку а не к заголовку. Правильнее было бы добавить тут padding: 2em; а вот у title сделать `margin: 0`.
Ну если там нужен отступ снизу то тогда `margin: 0 0 0 .1em`

2023-06-26 09:58 UTC, foxprogs commented on pricing_card/styles.css
> +  align-items: flex-end;
Да и `display: flex;` и `justify-content: center;` тут тоже ни к чему.

2023-06-26 10:01 UTC, foxprogs commented on pricing_card/styles.css
> +.reference a {
что это за стиль

2023-06-26 10:02 UTC, foxprogs commented on pricing_card/styles.css
> +.reference {
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/7608c744-97fb-46be-a3a0-0ecd836fea3b)
цвет ссылки не тот

2023-06-26 11:27 UTC, Yuriy2437 commented on pricing_card/styles.css
> +  position: relative;
Забегая вперед: во второй задаче, для кружка с крестиком, я позишны, всё же, оставил. Остальное решил на флексах.

2023-06-26 11:50 UTC, foxprogs approved these changes

2023-06-26 12:41 UTC, merged