Event Card #4
tt-dev-23/Yuriy2437_Practice pull request #9
Opened 2023-07-04 15:05 UTC by Yuriy2437

Верстка карточки с событием, #4

2023-07-05 06:38 UTC, foxprogs commented on event_card/index.html
> +          <div class="header"></div>
что это?

2023-07-05 06:39 UTC, foxprogs commented on event_card/index.html
> +          <h3 class="text2">Design</h3>
это не две фразы а одна, по этому должна быть в одном теге

2023-07-05 06:42 UTC, foxprogs commented on event_card/index.html
> +          <div class="content">
а почему это назвается контент?

2023-07-05 06:44 UTC, foxprogs commented on event_card/index.html
> +            <div class="avatar">
аватары

2023-07-05 06:50 UTC, foxprogs commented on event_card/index.html
> +                <div class="avatar1_inner avatar_inner_style"></div>
это убрать, вставить картинку <img src=...

2023-07-05 06:50 UTC, foxprogs commented on event_card/index.html
> +              <div class="avatar1_outer avatar_outer_style">
avatar1_outer, avatar2_outer, avatar3_outer удалить, без них можно сверстать

2023-07-05 06:51 UTC, foxprogs commented on event_card/index.html
> +              <div class="avatar1_outer avatar_outer_style">
avatar_outer_style слишком длинное, можно просто avatar

2023-07-05 06:53 UTC, foxprogs commented on event_card/styles.css
> +  align-items: center;
разве тут нужен флекс? Один див внутри

2023-07-05 07:04 UTC, foxprogs commented on event_card/styles.css
> +  align-items: flex-start;
не вижу эффекта от этих стилей, для чего они?

2023-07-05 07:06 UTC, foxprogs commented on event_card/styles.css
> +  display: flex;
для чего это?

2023-07-05 07:08 UTC, foxprogs commented on event_card/styles.css
> +  margin-top: 0.25rem;
1 - опять три стиля написаны, когда можно использовать сокращение
2- почему тут top и bottom, когда по макету эти отступы должен иметь родитель

2023-07-05 07:10 UTC, foxprogs commented on event_card/styles.css
> +  align-items: flex-end;
для чего это? Что оно дает?

2023-07-05 07:10 UTC, foxprogs commented on event_card/styles.css
> +  display: flex;
для чего тут флекс? Что он дает и почему нельзя без него?

2023-07-05 07:11 UTC, foxprogs commented on event_card/styles.css
> +  margin-top: -0.312rem;
это надо удалить, добавить правильный отступ у родителей

2023-07-05 07:11 UTC, foxprogs requested changes
нужны исправления

2023-07-05 09:56 UTC, Yuriy2437 commented on event_card/index.html
> +          <h3 class="text2">Design</h3>
Да, но по дизайну карточки она должна располагаться в двух строках. Если сделать в один тэг, то придется между Product и Design ставить <br/>. С ним сложнее регулировать расстояния между строками. Какой выход здесь вы предлагаете?

2023-07-05 09:57 UTC, Yuriy2437 commented on event_card/index.html
> +          <div class="content">
Он был так назван в аналогичном месте в прошлом задании. Какое название здесь будет правильным?

2023-07-05 09:58 UTC, Yuriy2437 commented on event_card/index.html
> +          <div class="header"></div>
случайно остался пустой класс с предыдущего макета, убираю

2023-07-05 10:02 UTC, Yuriy2437 commented on event_card/styles.css
> +  display: flex;
Следы неудачной попытки выравнивания иконки. Удаляю.

2023-07-05 10:08 UTC, Yuriy2437 commented on event_card/styles.css
> +  display: flex;
Вы правы. Без него здесь можно. Сформировалась неправильная привычка ставить флексы "на всякий случай" для выравнивания. Удаляю.

2023-07-05 10:12 UTC, Yuriy2437 commented on event_card/styles.css
> +  align-items: flex-end;
Вы правы. align-items: flex-end мало что здесь дает для вертикального выравнивания. Тогда как justify-content: space-between необходим для выравнивания горизонтального. Удаляю align-items: flex-end.

2023-07-05 10:16 UTC, Yuriy2437 commented on event_card/styles.css
> +  align-items: flex-start;
Cогласен. Следы неудачной попытки выравнивания иконки и текста. Удаляю

2023-07-05 10:25 UTC, Yuriy2437 commented on event_card/styles.css
> +  align-items: center;
Вы правы. Можно и без флекса здесь. Удаляю.

2023-07-05 12:05 UTC, Yuriy2437 commented on event_card/styles.css
> +  margin-top: -0.312rem;
Удалил margin-top: -0.312rem. Изменил в классе card_inner отступы на  padding: 2.54rem 2.54rem 2.25rem 2.54rem;

2023-07-05 12:23 UTC, Yuriy2437 commented on event_card/styles.css
> +  margin-top: 0.25rem;
1 - сделана сокращенная запись: margin: 0.25rem 0 0 0.3rem;
2 - убран здесь margin-bottom и добавлено к родительскому margin-bottom в классе content;
3 - margin-top здесь убирать нецелессобразно, так как он регулирует положение текста Oslo относительно иконки

2023-07-05 21:36 UTC, Yuriy2437 commented on event_card/index.html
> +            <div class="avatar">
поправил название

2023-07-05 21:36 UTC, Yuriy2437 commented on event_card/index.html
> +                <div class="avatar1_inner avatar_inner_style"></div>
вставил в новой версии

2023-07-05 21:39 UTC, Yuriy2437 commented on event_card/index.html
> +              <div class="avatar1_outer avatar_outer_style">
изменил все классы аватаров: имена и названия. Но оставил вложенность внешних классов белого ободка и внутренних классов картинок. Пока не понимаю, как убрать внешние классы, сохранив белый ободок?

2023-07-05 22:03 UTC, Yuriy2437 commented on event_card/index.html
> +              <div class="avatar1_outer avatar_outer_style">
Понял, как сделать. Убрал внешние классы вокруг аватарок. Реализовал через outline.

2023-07-05 22:53 UTC, Yuriy2437 commented on event_card/index.html
> +          <h3 class="text2">Design</h3>
Нашел выход. Объединил классы text1 и text2 в класс text и обратился к двум его элементам в CSS через .text:nth-child(2) и .text:nth-child(3)

2023-07-05 22:54 UTC, Yuriy2437 commented on event_card/index.html
> +          <div class="content">
Переименовал content в logo

2023-07-06 20:17 UTC, foxprogs commented on event_card/index.html
> +          <h3 class="text2">Design</h3>
Надо сделать в одном теге h3, не в двух. Расстояние между строками регулируется через line-height.

2023-07-06 20:19 UTC, foxprogs commented on event_card/index.html
> +          <div class="content">
надо давать название по смыслу. Это не содержимое карточки, это не логотип. Тут указано название города с иконкой местоположения. Значит можно дать название "локация" к примеру. Это же карточка события

2023-07-06 20:25 UTC, foxprogs commented on event_card/styles.css
> +  margin-top: 0.25rem;
текст и иконку надо выровнять через флексы у родителя

2023-07-06 20:26 UTC, foxprogs commented on event_card/index.html
> +          <h6 class="text_header">Wed, Nov 24, 20121 • 6:00 CEST</h6>
по идее это тоже не заголовок а дата и время

2023-07-06 20:27 UTC, foxprogs commented on event_card/index.html
> +          <h3 class="text">Design</h3>
объединить в один h3

2023-07-06 20:29 UTC, foxprogs commented on event_card/index.html
> +              <img src="https://i.pravatar.cc/43" class="avatar rim_margin" />
можно без классов `avatar` и `rim_margin` сделать же. вместо `avatar` `avatars img` а подвинуть друг к другу через псевдокрассы к примеру. все сделать со смещением а у первого его убрать

2023-07-06 20:31 UTC, foxprogs commented on event_card/index.html
> +              <img src="https://i.pravatar.cc/43" class="avatar rim_margin" />
я писал что картинки надо 32 пикселя, а почему тут 42, 43 и 44 пикселя?

2023-07-06 20:37 UTC, foxprogs commented on event_card/styles.css
> +  outline: 0.25rem solid #fff;
толстая очень обводка

2023-07-07 21:36 UTC, Yuriy2437 commented on event_card/index.html
> +          <h3 class="text2">Design</h3>
сделано в одном теге h3

2023-07-07 21:36 UTC, Yuriy2437 commented on event_card/index.html
> +          <div class="content">
Название logo изменено на location

2023-07-07 21:39 UTC, Yuriy2437 commented on event_card/index.html
> +          <h3 class="text">Design</h3>
объединил в один h3

2023-07-07 21:48 UTC, Yuriy2437 commented on event_card/styles.css
> +  outline: 0.25rem solid #fff;
уменьшил до 0.15rem

2023-07-07 21:51 UTC, Yuriy2437 commented on event_card/index.html
> +              <img src="https://i.pravatar.cc/43" class="avatar rim_margin" />
Извините, не увидел, что 42, 43 и 44 - это не номера картинок, а пиксели. Все равно заданием width и height в классе avatar они урезаются до 32 пикселей. Тем не менее, я поменял ссылки на 32,33 и 34. Одну ссылку 32 сделать не могу, так как тогда получаются три одинаковые аватарки

2023-07-07 21:54 UTC, Yuriy2437 commented on event_card/index.html
> +          <h6 class="text_header">Wed, Nov 24, 20121 • 6:00 CEST</h6>
Поменял text_header на date_time

2023-07-07 22:31 UTC, Yuriy2437 commented on event_card/index.html
> +              <img src="https://i.pravatar.cc/43" class="avatar rim_margin" />
Сделал один класс avatars. Смещение-наплыв реализовал через отрицательный отступ у margin в подклассе avatars img

2023-07-08 08:36 UTC, Yuriy2437 commented on event_card/styles.css
> +  margin-top: 0.25rem;
Добавил в класс location align-items: center. Убрал из класса address верхний отступ 0.25. Теперь там margin: 0 0 0 0.3rem;

2023-07-10 15:38 UTC, foxprogs commented on event_card/index.html
> +              <img src="https://i.pravatar.cc/43" class="avatar rim_margin" />
![изображение](https://github.com/tt-dev-23/Yuriy2437_Practice/assets/30548361/ab22bd42-5859-45c5-808c-dcccaec0e60d)
Если зайти на сайт то там можно увидеть как именно можно получить разные картинки через дополнительные параметры в юрл. Картинки не урезаются до 32 а сжимаются. Если картинка 33 пикселя а ее надо сделать 32, то качество 100% испортится, так как не существует половинчатых пикселей. Пиксель - это точка на экране. Соответственно чтобы 33 пикселя превратить в 32 надо либо просто один удалить в каждой строке и столбце или же применть алгоритм который рассчитает новые цвета каждого пикселя.

2023-07-10 15:41 UTC, foxprogs commented on event_card/styles.css
> +  height: 1.75rem;
размер 28 а надо 32 сделать

2023-07-10 16:31 UTC, Yuriy2437 commented on event_card/styles.css
> +  margin-bottom: 0;
сделано

2023-07-10 16:31 UTC, Yuriy2437 commented on event_card/styles.css
> +  height: 1.75rem;
Увеличено до 2rem

2023-07-10 16:37 UTC, Yuriy2437 commented on event_card/index.html
> +              <img src="https://i.pravatar.cc/43" class="avatar rim_margin" />
Изменены ссылки на аватарки: https://i.pravatar.cc/32?img=1, https://i.pravatar.cc/32?img=2, https://i.pravatar.cc/32?img=3

2023-07-10 16:50 UTC, foxprogs approved these changes

2023-07-10 16:52 UTC, merged